sudo: false
language: java
install: /bin/true
script: ./.utility/travis.sh
jdk:
- oraclejdk8
- oraclejdk7
cache:
  directories:
  - $HOME/.m2/repository
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_a973fe4f8e79_key -iv $encrypted_a973fe4f8e79_iv -in config.properties.enc -out src/test/resources/config.properties -d || true'
- pip install --user codecov
notifications:
  email: false
env:
  global:
  - secure: VvKBWj1OCu7SH+utwqe7kdli0N7jTYQ7D/citdFIV0cDjpcX3MwxfPcIeMvOuWLgJKaOSD4xnG9pOgMoLMMCGcsCHa2bqx78clA8t4sV7I0sx8pSN2Iuj/wQJvNV3/uEETC84+P9hKIt+o8JZqhgC1GEpz5fbyKyUIlRkspW1WQ=
after_success:
- codecov
- mvn javadoc:javadoc
- .utility/push-javadoc-to-gh-pages.sh
